name: Docker Image Create-Update-Publish-Deploy

on:
  push:
    branches: [ "main" ]
env:
  REGISTRY: ghcr.io
jobs:
  publish:
    name: publish image
    runs-on: self-hosted

    steps:
    - name: set lower case owner name
      run: |
        echo "github_owner=`echo ${{github.actor}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}
    - name: set image name
      run: |
        echo "IMAGE_NAME=`echo ${{ env.github_owner }}/hello-world:latest`" >>${GITHUB_ENV}
    - uses: actions/checkout@v3
    - name: Login
      run: |
        echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build the Docker image and Publish
      run: |
        docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

  deploy:
    needs: publish
    name: deploy image
    runs-on: self-hosted

    steps:
    - name: set lower case owner name
      run: |
        echo "github_owner=`echo ${{github.actor}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}
    - name: set image name
      run: |
        echo "IMAGE_NAME=`echo ${{ env.github_owner }}/hello-world:latest`" >>${GITHUB_ENV}
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        name: id_rsa # optional
        known_hosts: ${{ secrets.SSH_HOST }}
        if_key_exists: ignore
    - name: connect it and publish
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} && docker run -it -p 80:80 ${{ env.IMAGE_NAME }}"
    - name: cleanup step
      run: rm -rf ~/.ssh
  
